---
title: "NYC Restaurant Inspections Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
```

```{r}
data("rest_inspec") 

rest_inspect_sample <- 
  rest_inspec |> 
  drop_na() |> 
  slice_sample(n = 500)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspect_sample |> 
  count(grade) |> 
  mutate(grade = fct_reorder(grade, n)) |> 
  plot_ly(x = ~grade, y = ~n, color = ~grade, type = "bar")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspect_sample |> 
  mutate(boro = fct_reorder(boro, score)) |> 
  plot_ly(y = ~score, color = ~boro, type = "box")
```

### Chart C

```{r}
rest_inspect_sample |> 
  plot_ly(x = ~inspection_date, y = ~score, type = "scatter", mode = "markers", 
          color = ~critical_flag)
```

